project_id = "dnjzkewlixghwwculbsf"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.admin-pro]
verify_jwt = false

[functions.check-pro]
verify_jwt = false

[functions.redeem-code]
verify_jwt = false
